name: RefiningCore
version: '${project.version}'
main: git.austxnsheep.refiningcore.RefiningCore
api-version: '1.20'

commands:
  refiner:
    description: Opens the gui used for refining stuff
    usage: /refiner